query Users($id: String!) {
  user(id: $id) {
    id
    name
    icon_image
    company
    hp
    mp
    technology
    achievement
    motivation
    solution
    plan
    design
    exp

    groups {
      id

      project {
        id
        name
        overview
        created_at
        end_date
        project_end_flg
        difficulty

        groups {
          id

          user {
            id
            name
            icon_image
            occupation_id
          }
        }

        monster {
          id
          name
          story

          specie {
            id
            name
          }
        }
      }
    }
  }
}

mutation SearchSameCompanyUsers($selectUserIds: [String!]!, $name: String!, $company: String!) {
  searchSameCompanyUsers(
    conditionSearchUser: { ids: $selectUserIds, name: $name, company: $company }
  ) {
    id
    name
    icon_image
    occupation_id
  }
}

mutation CreateProject(
  $name: String!
  $overview: String!
  $difficulty: Float!
  $end_date: String!
  $ids: [String!]!
) {
  createProject(
    newProject: {
      name: $name
      overview: $overview
      hp: 0
      difficulty: $difficulty
      end_date: $end_date
      project_end_flg: false
    }
    selectUser: { ids: $ids }
  ) {
    id
    name
    overview
  }
}

query GetInvitations($userId: String!) {
  invitations(userId: $userId) {
    id

    project {
      id
      name
    }
  }
}
