query GetProject($id: String!) {
  getProjectById(id: $id) {
    id
    name
    hp
    difficulty

    gameLogs {
      id
      context
      created_at

      user {
        id
        name
      }
    }

    monster {
      id
      name
    }

    groups {
      user {
        id
        name
        icon_image
        hp
        mp
        exp
        technology
        achievement
        motivation
        solution
        plan
        design
        occupation_id
        online_flg
        interests {
          id
          context
        }
        certifications {
          id
          name
        }
      }
    }

    lists {
      id
      list_id
      name

      listSorts {
        id
        task_list
      }

      tasks {
        id
        title
        overview
        technology
        achievement
        solution
        motivation
        plan
        design
        vertical_sort
        end_date
        chatCount

        allocations {
          id

          user {
            id
            name
            icon_image
          }
        }
      }
    }
  }
}

query SearchUsers($searchUser: ProjectDetailUserSearchInput!) {
  findProjectDetailSameCompanyUsers(searchUser: $searchUser) {
    id
    name
    icon_image

    invitations {
      id
    }
  }
}

mutation UpdateOnlineFlag($id: String!, $isOnline: Boolean!) {
  updateOnlineFlag(id: $id, isOnline: $isOnline) {
    id
    name
    online_flg
  }
}

mutation CreateInvitation($userId: String!, $projectId: String!) {
  createInvitation(userId: $userId, projectId: $projectId) {
    id

    user {
      id
      name
    }
  }
}

query GetListsByProjectId($projectId: String!) {
  listsByProjectId(projectId: $projectId) {
    id
    list_id
    name

    listSorts {
      id
      task_list
    }

    tasks {
      id
      title
      overview
      technology
      achievement
      solution
      motivation
      plan
      design
      vertical_sort
      end_date
      chatCount

      allocations {
        id

        user {
          id
          name
          icon_image
        }
      }
    }
  }
}

mutation UpdateTaskSort($updateTasks: UpdateTaskSort!) {
  updateTaskSort(updateTask: $updateTasks) {
    id
    overview
  }
}

mutation AddTask($newTask: NewTaskInput!) {
  addTask(newTask: $newTask) {
    id
    overview
  }
}

mutation CreateList($name: String!, $project_id: String!, $task_list: Float!) {
  createList(newList: { name: $name, project_id: $project_id, task_list: $task_list }) {
    id
    list_id
    name

    listSorts {
      id
      task_list
    }

    tasks {
      id
      title
      overview
      technology
      achievement
      solution
      motivation
      plan
      design
      vertical_sort
      end_date
      chatCount

      allocations {
        id

        user {
          id
          name
          icon_image
        }
      }
    }
  }
}

mutation UpdateListSort($listSort: [UpdateListSortObject!]!) {
  updateListSort(updateListSort: { listSort: $listSort })
}

mutation UpdateListName($name: String!, $list_id: String!) {
  updateListName(updateList: { name: $name, list_id: $list_id }) {
    name
    list_id
  }
}

mutation RemoveList($id: Float!) {
  removeList(removeList: { id: $id })
}
