query GetProject($id: Float!) {
  getProjectById(id: $id) {
    id
    name
    hp
    difficulty

    groups {
      user {
        id
        name
        hp
        mp
        occupation_id
        icon_image
        online_flg
      }
    }

    lists {
      id
      list_id
      name

      listSorts {
        id
        task_list
      }

      tasks {
        id
        overview
        explanation
        technology
        achievement
        solution
        motivation
        plan
        design
        weight
        vertical_sort
        end_date

        allocations {
          id

          user {
            id
            name
            icon_image
          }
        }
      }
    }
  }
}

mutation UpdateOnlineFlag($id: String!, $isOnline: Boolean!) {
  updateOnlineFlag(id: $id, isOnline: $isOnline) {
    id
    name
    online_flg
  }
}

mutation CreateInvitation($userId: String!, $projectId: String!) {
  createInvitation(userId: $userId, projectId: $projectId) {
    id

    user {
      id
      name
    }
  }
}

query GetListsByProjectId($projectId: String!) {
  listsByProjectId(projectId: $projectId) {
    id
    list_id
    name

    listSorts {
      id
      task_list
    }

    tasks {
      id
      overview
      explanation
      technology
      achievement
      solution
      motivation
      plan
      design
      weight
      vertical_sort
      end_date

      allocations {
        id

        user {
          id
          name
          icon_image
        }
      }
    }
  }
}

mutation UpdateTaskSort($updateTasks: UpdateTaskSort!) {
  updateTaskSort(updateTask: $updateTasks) {
    id
    overview
  }
}

mutation AddTask($newTask: NewTaskInput!) {
  addTask(newTask: $newTask) {
    id
    overview
  }
}
