mutation AddUser(
  $id: String!
  $name: String!
  $icon_image: String!
  $companies_id: Float!
  $occupation_id: Float!
) {
  addUser(
    newUser: {
      id: $id
      name: $name
      icon_image: $icon_image
      online_flg: true
      hp: 100
      mp: 100
      occupation_id: $companies_id
      companies_id: $occupation_id
      memo: ""
      technology: 0
      achievement: 0
      motivation: 0
      solution: 0
      plan: 0
      design: 0
      exp: 0
    }
  ) {
    id
    name
    icon_image
    online_flg
    hp
    mp
    occupation_id
    companies_id
    memo
    technology
    achievement
    motivation
    solution
    plan
    design
    exp
  }
}

mutation AddQualification($user_id: String!, $name: String!) {
  addQualification(newQualification: { user_id: $user_id, name: $name }) {
    user_id
    name
  }
}

mutation AddInterest($user_id: String!, $context: String!) {
  addInterest(newInterest: { user_id: $user_id, context: $context }) {
    user_id
    context
  }
}
