mutation AddUser(
  $id: String!
  $name: String!
  $icon_image: String!
  $occupation_id: Float!
  $company: String!
  $context: [String!]!
  $certificationName: [String!]!
) {
  addUser(
    newUser: {
      id: $id
      name: $name
      icon_image: $icon_image
      online_flg: false
      hp: 100
      mp: 100
      occupation_id: $occupation_id
      company: $company
      memo: ""
      technology: 0
      achievement: 0
      motivation: 0
      solution: 0
      plan: 0
      design: 0
      exp: 0
    }
    newInterest: { context: $context }
    newCertification: { name: $certificationName }
  ) {
    id
    name
    icon_image
    online_flg
    hp
    mp
    company
    memo
    technology
    achievement
    motivation
    solution
    plan
    design
    exp

    occupation {
      id
      name
    }
  }
}
