query GetProject($id: String!) {
  getProjectById(id: $id) {
    id
    name
    hp
    difficulty

    monster {
      id
      name
    }

    groups {
      user {
        id
        name
        icon_image
        hp
        mp
        exp
        technology
        achievement
        motivation
        solution
        plan
        design
        online_flg

        interests {
          id
          context
        }

        certifications {
          id
          name
        }

        occupation {
          id
          name
        }
      }
    }

    lists {
      id
      list_id
      name

      listSorts {
        id
        task_list
      }

      tasks {
        id
        title
        overview
        technology
        achievement
        solution
        motivation
        plan
        design
        vertical_sort
        end_date
        chatCount
        completed_flg

        allocations {
          id

          user {
            id
            name
            icon_image
            occupation {
              id
              name
            }
          }
        }
      }
    }
  }
}

query SearchUsers($searchUser: ProjectDetailUserSearchInput!) {
  findProjectDetailSameCompanyUsers(searchUser: $searchUser) {
    id
    name
    icon_image

    invitations {
      id
    }
  }
}

query GetGameLogsByProjectId($project_id: String!) {
  findLogsByProjectId(project_id: $project_id) {
    id
    context
    created_at

    user {
      id
      name
    }
  }
}

mutation UpdateOnlineFlag($id: String!, $project_id: String!, $isOnline: Boolean!) {
  updateOnlineFlag(id: $id, project_id: $project_id, isOnline: $isOnline) {
    id
    name
    online_flg
  }
}

mutation CreateInvitation($userId: String!, $projectId: String!) {
  createInvitation(userId: $userId, projectId: $projectId) {
    id

    user {
      id
      name
    }
  }
}

query GetListsByProjectId($projectId: String!) {
  listsByProjectId(projectId: $projectId) {
    id
    list_id
    name

    listSorts {
      id
      task_list
    }

    tasks {
      id
      title
      overview
      technology
      achievement
      solution
      motivation
      plan
      design
      vertical_sort
      end_date
      chatCount

      allocations {
        id

        user {
          id
          name
          icon_image
          occupation {
            id
            name
          }
        }
      }
    }
  }
}

mutation UpdateTaskSort($updateTasks: UpdateTaskSort!) {
  updateTaskSort(updateTask: $updateTasks) {
    id
    overview
  }
}

mutation UpdateTaskTitle($taskId: Float!, $title: String!) {
  updateTaskTitle(taskId: $taskId, title: $title) {
    title
  }
}

mutation UpdateTaskOverview($taskId: Float!, $overview: String!) {
  updateTaskOverview(taskId: $taskId, overview: $overview) {
    overview
  }
}

mutation UpdateTaskParameters(
  $taskId: Float!
  $design: Float!
  $plan: Float!
  $motivation: Float!
  $solution: Float!
  $achievement: Float!
  $technology: Float!
) {
  updateTaskParameters(
    taskId: $taskId
    design: $design
    plan: $plan
    motivation: $motivation
    solution: $solution
    achievement: $achievement
    technology: $technology
  ) {
    id
    design
    plan
    motivation
    solution
    achievement
    technology
  }
}

mutation UpdateTaskEndDate($taskId: Float!, $end_date: String!) {
  updateTaskEndDate(taskId: $taskId, end_date: $end_date) {
    id
    end_date
  }
}

mutation CreateAllocation($newAllocation: NewAllocationInput!) {
  createAllocation(newAllocation: $newAllocation) {
    user {
      id
      name
      icon_image
      # occupation {
      #   id
      #   name
      # }
    }
  }
}

mutation UnAssignTask($taskId: Float!, $userId: String!) {
  unAssignTask(task_id: $taskId, user_id: $userId) {
    user {
      id
      name
      icon_image
      # occupation {
      #   id
      #   name
      # }
    }
  }
}

mutation AddTask($newTask: NewTaskInput!, $assignTask: AssignTaskInput!) {
  addTask(newTask: $newTask, assignTask: $assignTask) {
    id
    overview
  }
}

mutation DeleteTask($taskId: Float!) {
  deleteTask(taskId: $taskId) {
    id
  }
}

mutation CreateList($newList: NewListInput!) {
  createList(newList: $newList) {
    id
    list_id
    name

    listSorts {
      id
      task_list
    }

    tasks {
      id
      title
      overview
      technology
      achievement
      solution
      motivation
      plan
      design
      vertical_sort
      end_date
      chatCount

      allocations {
        id

        user {
          id
          name
          icon_image
          occupation {
            id
            name
          }
        }
      }
    }
  }
}

mutation UpdateListSort($listSort: [UpdateListSortObject!]!) {
  updateListSort(updateListSort: { listSort: $listSort })
}

mutation UpdateListName($name: String!, $list_id: String!) {
  updateListName(updateList: { name: $name, list_id: $list_id }) {
    name
    list_id
  }
}

mutation RemoveList($id: Float!) {
  removeList(removeList: { id: $id })
}

query GetChats($taskId: Float!) {
  getChats(taskId: $taskId) {
    id
    comment
    user {
      id
      name
      icon_image
      # occupation {
      #   id
      #   name
      # }
    }
    created_at
    updated_at
  }
}

mutation AddChat($taskId: Float!, $userId: String!, $comment: String!) {
  addChat(userId: $userId, taskId: $taskId, comment: $comment) {
    id
    comment
    user {
      id
      name
      icon_image
      # occupation {
      #   id
      #   name
      # }
    }
    created_at
    updated_at
  }
}

mutation UpdateChat($taskId: Float!, $chatId: Float!, $comment: String!) {
  updateChat(taskId: $taskId, comment: $comment, chatId: $chatId) {
    id
    comment
    user {
      id
      name
      icon_image
      # occupation {
      #   id
      #   name
      # }
    }
    created_at
    updated_at
  }
}

mutation DeleteChat($taskId: Float!, $chatId: Float!) {
  deleteChat(taskId: $taskId, chatId: $chatId) {
    id
    comment
    user {
      id
      name
      icon_image
      # occupation {
      #   id
      #   name
      # }
    }
    created_at
    updated_at
    deleted_at
  }
}
