/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { AnimationClip } from 'three'
import { useFrame } from '@react-three/fiber'
import logger from 'utils/debugger/logger'

type GLTFResult = GLTF & {
  nodes: {
    Eyes003: THREE.Mesh
    Drago_Simple: THREE.SkinnedMesh
    CG: THREE.Bone
  }
  materials: {
    ['Material #240']: THREE.MeshStandardMaterial
    ['Material #284']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Idle' | 'eat'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const ref = useRef<any>()
  const { nodes, materials, animations } = useGLTF('/cg/dragonIdle.glb') as GLTFResult
  const { actions } = useAnimations<AnimationClip>(animations, group)
  useFrame(() => {
    if (!ref.current) return
    ref.current.rotation.y += 0.01
  })
  useEffect(() => {
    logger.debug(actions)
    actions['Idle']?.play()
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.05, 0.25, 0.02]} rotation={[-0.03, -1.49, 0.06]} scale={0.01} ref={ref}>
        <primitive object={nodes.CG} />
        <skinnedMesh
          geometry={nodes.Drago_Simple.geometry}
          material={materials['Material #284']}
          skeleton={nodes.Drago_Simple.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/cg/dragonIdle.glb')
