query GetUser($id: String!) {
  user(id: $id) {
    id
    name
    icon_image
    online_flg
    hp
    mp
    company
    memo
    technology
    achievement
    motivation
    solution
    plan
    design
    exp

    occupation {
      id
      name
    }

    interests {
      id
      context
    }

    certifications {
      id
      name
    }

    invitations {
      id
      created_at

      project {
        id
        name
      }
    }
  }
}

mutation UpdateCertification($newCertification: NewCertificationInput!) {
  addCertification(newCertification: $newCertification) {
    id
    name
    user {
      id
      name
    }
  }
}

mutation UpdateInterests($newInterest: NewInterestInput!) {
  addInterest(newInterest: $newInterest) {
    id
    context
    user {
      id
      name
    }
  }
}
