query GetUser($id: String!) {
  user(id: $id) {
    id
    name
    icon_image
    online_flg
    hp
    mp
    company
    memo
    technology
    achievement
    motivation
    solution
    plan
    design
    exp

    occupation {
      id
      name
    }

    interests {
      id
      context
    }

    certifications {
      id
      name
    }

    invitations {
      id
      created_at

      project {
        id
        name
      }
    }
  }
}

mutation UpdateUserName($name: String!, $id: String!) {
  updateUserName(name: $name, id: $id) {
    id
    name
    icon_image
  }
}

mutation UpdateUserIconImage($icon_image: String!, $id: String!) {
  updateUserIconImage(icon_image: $icon_image, id: $id) {
    id
    name
    icon_image
  }
}

mutation UpdateCertifications($names: [String!]!, $user_id: String!) {
  updateCertifications(names: $names, user_id: $user_id) {
    id
    name
  }
}

mutation UpdateInterests($contexts: [String!]!, $user_id: String!) {
  updateInterests(contexts: $contexts, user_id: $user_id) {
    id
    context
  }
}
