query GetUser($id: String!) {
  user(id: $id) {
    id
    name
    icon_image
    online_flg
    hp
    mp
    occupation_id
    company
    memo
    technology
    achievement
    motivation
    solution
    plan
    design
    exp

    interests {
      context
    }

    qualifications {
      name
    }
  }
}
